food/urls.py
from django.urls import path
from food import views

app_name = 'food'

urlpatterns = [
    
    path('', views.index, name='index'), # url ---> /food/
    path('<int:item_id>',views.detail, name='detail'), # url ---> /food/1
    path('add',views.create_item,name='create_item'),   # url ---> /food/add
    path('update/<int:id>',views.update_item,name='update_item'),   # url ---> /food/update/1
    path('delete/<int:id>',views.delete_item,name='delete_item'),   # url ---> /food/delete/1
]

food_menu/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as authentication_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', include('users.urls')),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profile,name='profile'),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    
    path('', views.register_users, name='register_users'), # url ---> /register

]

food/models.py
from pyexpat import model
from django.db import models

# Create your models here.
class Item(models.Model):
    item_name = models.CharField(max_length=255)
    item_description = models.CharField(max_length=255)
    price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg")

    def __str__(self):
        return self.item_name

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    

food/forms.py
from django import forms
from food.models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_description', 'price', 'item_image']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.models import User 

class RegisterUserForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from re import template
from django.shortcuts import render, redirect
from food.models import Item
from django.template import loader
from food.forms import ItemForm
# Create your views here.

def index(request):
    item_list = Item.objects.all()
    context = { 'item_list': item_list }
    return render(request,'food/index.html',context)

def detail(request,item_id):
    item_detail = Item.objects.get(pk=item_id)
    context = {'item_detail': item_detail}
    return render(request,'food/detail.html',context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    context = {'form': form}

    return render(request,'food/item-form.html',context)


def update_item(request,id):
    item = Item.objects.get(pk=id)
    form = ItemForm(request.POST or None,instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    context = {'form': form, 'item': item}

    return render(request,'food/item-form.html',context)


def delete_item(request,id):
    item = Item.objects.get(pk=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    context = {'item': item}

    return render(request, 'food/delete-item.html',context)
    
    

users/views.py
from contextlib import redirect_stderr
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm 
from django.contrib import messages
from users.forms import RegisterUserForm

from django.contrib.auth.decorators import login_required
# Create your views here.



def register_users(request):

    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            message = "Welcome {} your Account has been created!!" .format(username)
            messages.success(request,message)
            return redirect('login')
    else:
        form = RegisterUserForm()
    
    context = {'form': form}
    return render(request,'users/register.html',context)

@login_required
def profile(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">FOOD APP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
           <ul class="navbar-nav justify-content-center">
              <li class="nav-item active">
                 <a class="nav-link" href="{% url 'food:create_item' %}">ADD ITEM</a>
              </li>
              <li class="nav-item">
                 <a class="nav-link" href="#">VIEW ITEM</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="#">DELETE ITEM</a>
             </li>
             <li class="nav-item">
                {% if user.is_authenticated %}
                  <a class="nav-link" href="{% url 'logout' %}">LOGOUT</a>
                  <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                {% else  %}
                <a class="nav-link" href="{% url 'login' %}">LOGIN</a>
                {% endif %}

            </li>
           </ul>
        </div>
     </nav>


     {% if messages %}

     {% for message in messages %}
      {{ message }}
      {% endfor %}

     {% endif %}
    
{% block body %}
    
{% endblock %}
</body>
</html>

food/templates/food/delete-item.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to Delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

food/templates/food/detail.html
{% extends "food/base.html" %}

{% block body %}

<div class= "container">
    <div class="row">
        <div class="col-md-6">
            <img height="100px" src="{{item_detail.item_image}}" class="img-thumbnail">
        </div>

        <div class="col-md-6">
            <h1>{{ item_detail.item_name }}</h1>
            <h2>{{ item_detail.item_description }}</h2>
            <h2>Rs.{{ item_detail.price }}</h2>
            <a href="{% url 'food:delete_item' item_detail.id %}">Delete</a>
        </div>

    </div>
</div>



{% endblock %}

food/templates/food/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
{% extends "food/base.html" %}

<body>
{% block body %}


{% for item in item_list %}



<br>
<div class="container-fluid">
    <div class="row">
      <div class="col-xl-6 col-lg-6 col-md-6">
        <img src="{{ item.item_image }}"  class="img-fluid" height="150px">
      </div>
      
      <div class="col-xl-6 col-lg-6 col-md-6">
        <h3>{{ item.item_name }}</h3>
        <h3>{{ item.item_description }}</h3>
        <h3>{{ item.price }}</h3>
        <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
      </div>

    </div>
  </div>

{% endfor %}


{% endblock %}
</body>
</html>

food/templates/food/item-form.html
{% extends "food/base.html" %}

{% block body %}

<form method="POST">
    {% csrf_token %}

    {{ form }}

    <button type="submit">Save</button>


</form>

{% endblock %}

users/templates/users/login.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>
</form>

users/templates/users/logout.html
<h2>You have been Logged out.</h2>

users/templates/users/profile.html
<h1>{{ user.username }}</h1>

users/templates/users/register.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Sign up</button>
</form>